% Integratable with IteratePath.
% Should TargetCP raw data files not include information regarding the
% scene size, this method adds them.
function TargetCPAmendments(filePath)
    targetCP = load(filePath);
    if contains(filePath, "panel_truck", "IgnoreCase", true)
        targetCP.sceneSize = 15;
    elseif contains(filePath, "brud", "IgnoreCase", true) ...
        || contains(filePath, "dihed", "IgnoreCase", true) ...
        || contains(filePath, "scr1", "IgnoreCase", true) ...
        || contains(filePath, "str01_1", "IgnoreCase", true) ...
        || contains(filePath, "str02_1", "IgnoreCase", true) ...
        || contains(filePath, "tophat1", "IgnoreCase", true) ...
        || contains(filePath, "tophat2a", "IgnoreCase", true) ...
        || contains(filePath, "tophat2b", "IgnoreCase", true) ...
        || contains(filePath, "tophat3", "IgnoreCase", true) ...
        || contains(filePath, "tri", "IgnoreCase", true)
        targetCP.sceneSize = 5;
    else
        targetCP.sceneSize = 10;
    end

    outPath = strcat(GetOutputPath(filePath), ".mat");
    save(outPath, "-struct", "targetCP", "-v7.3");
end